#!/bin/sh
#
# COMMAND LINE ANIMATIONS WOOHOO
# https://github.com/holman/gifme
#
#
#/ USAGE: gifme [<options>] FILES
#/
#/ Options:
#/   - r: Adds a reversing effect after the initial animation.
#/
#/ Examples:
#/
#/   # Animate a group of files
#/   gifme ~/Desktop/images
#/
#/   # Animate from a movie
#/   gifme ~/Desktop/movie.mp4 <start> <duration>
#/
#/   # Animate a YouTube (eventually)
#/   gifme http://www.youtube.com/watch?v=-Zzh79J2fC0

set -e
set -o posix

# Print help/usage with no pattern/args
test $# -eq 0 -o "$1" = "--help" && {
    cat $0 | grep '^#/' | cut -c4-
    exit 0
}

# Should we actually run ffmpeg?
noop=false

# Get and set options
while getopts n opt; do
  case "$opt" in
    n)  noop=true;;
  esac
done

cmd='cmd'

# If we're in test, don't actually run the command
if $noop
then
  echo $cmd
  exit 0
fi

$($cmd)